"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class ref_upper_dof_pos_lcmt(object):

    __slots__ = ["ref_upper_dof_pos"]

    __typenames__ = ["double"]

    __dimensions__ = [[14]]

    def __init__(self):
        self.ref_upper_dof_pos = [ 0.0 for dim0 in range(14) ]
        """ LCM Type: double[14] """

    def encode(self):
        buf = BytesIO()
        buf.write(ref_upper_dof_pos_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>14d', *self.ref_upper_dof_pos[:14]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != ref_upper_dof_pos_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return ref_upper_dof_pos_lcmt._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = ref_upper_dof_pos_lcmt()
        self.ref_upper_dof_pos = struct.unpack('>14d', buf.read(112))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if ref_upper_dof_pos_lcmt in parents: return 0
        tmphash = (0x53306678b590ccc1) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if ref_upper_dof_pos_lcmt._packed_fingerprint is None:
            ref_upper_dof_pos_lcmt._packed_fingerprint = struct.pack(">Q", ref_upper_dof_pos_lcmt._get_hash_recursive([]))
        return ref_upper_dof_pos_lcmt._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", ref_upper_dof_pos_lcmt._get_packed_fingerprint())[0]

