"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class motor_safety_state_lcmt(object):
    __slots__ = ["tau_est", "temperature", "motor_state", "timestamp_us"]

    def __init__(self):
        self.tau_est = [ 0.0 for dim0 in range(29) ]
        self.temperature = [ 0 for dim0 in range(58) ]
        self.motor_state = [ 0 for dim0 in range(29) ]
        self.timestamp_us = 0

    def encode(self):
        buf = BytesIO()
        buf.write(motor_safety_state_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>29f', *self.tau_est[:29]))
        buf.write(struct.pack('>58h', *self.temperature[:58]))
        buf.write(struct.pack('>29i', *self.motor_state[:29]))
        buf.write(struct.pack(">q", self.timestamp_us))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != motor_safety_state_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return motor_safety_state_lcmt._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = motor_safety_state_lcmt()
        self.tau_est = struct.unpack('>29f', buf.read(116))
        self.temperature = struct.unpack('>58h', buf.read(116))
        self.motor_state = struct.unpack('>29i', buf.read(116))
        self.timestamp_us = struct.unpack(">q", buf.read(8))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if motor_safety_state_lcmt in parents: return 0
        tmphash = (0xffe0ec165e03e079) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if motor_safety_state_lcmt._packed_fingerprint is None:
            motor_safety_state_lcmt._packed_fingerprint = struct.pack(">Q", motor_safety_state_lcmt._get_hash_recursive([]))
        return motor_safety_state_lcmt._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

